import { Author } from './models';

export const authors: Author[] = [
  {
    fullname: 'Alessandro Bianchi',
    birthdate: '10/05/1980',
    age: 42,
    fiscalcode: 'BCDALD80M01H501Z',
    address: 'Via Roma, 123',
    placeOfBirth: 'Roma',
    nationality: 'Italiana',
    bio: "Appassionato di astronomia fin dall'infanzia, Alessandro Bianchi ha dedicato la sua vita allo studio degli astri e all'esplorazione spaziale.",
    sex: 'M',
    eyeColor: 'Marroni',
    hairColor: 'Neri',
    height: 175,
    publishedArticles: 20,
    firstPublishDate: 2002,
    specialization: 'Astronomia',
  },
  {
    fullname: 'Giulia Moretti',
    birthdate: '15/08/1985',
    age: 37,
    fiscalcode: 'MRTGLI85M45H501W',
    address: 'Via Milano, 456',
    placeOfBirth: 'Milano',
    nationality: 'Italiana',
    bio: "Giulia Moretti è un'appassionata sostenitrice delle innovazioni mediche. Scrive per rendere accessibili a tutti le ultime scoperte e tecnologie nel campo della medicina.",
    sex: 'F',
    eyeColor: 'Verdi',
    hairColor: 'Biondi',
    height: 162,
    publishedArticles: 15,
    firstPublishDate: 2008,
    specialization: 'Medicina',
  },
  {
    fullname: 'Luca De Santis',
    birthdate: '20/03/1982',
    age: 40,
    fiscalcode: 'DSTLCU82M20H501Y',
    address: 'Via Napoli, 789',
    placeOfBirth: 'Napoli',
    nationality: 'Italiana',
    bio: "Esperto archeologo, Luca De Santis ha dedicato la sua carriera alla scoperta di antiche civiltà e all'analisi di reperti storici.",
    sex: 'M',
    eyeColor: 'Azzurri',
    hairColor: 'Castani',
    height: 180,
    publishedArticles: 18,
    firstPublishDate: 2004,
    specialization: 'Archeologia',
  },
  {
    fullname: 'Martina Russo',
    birthdate: '05/11/1987',
    age: 35,
    fiscalcode: 'RSSMRT87M05H501V',
    address: 'Via Firenze, 234',
    placeOfBirth: 'Firenze',
    nationality: 'Italiana',
    bio: "Martina Russo è una studiosa di intelligenza artificiale. Esplora le implicazioni etiche e sociali dell'IA nel nostro mondo in evoluzione.",
    sex: 'F',
    eyeColor: 'Verdi',
    hairColor: 'Neri',
    height: 168,
    publishedArticles: 22,
    firstPublishDate: 2006,
    specialization: 'Intelligenza Artificiale',
  },
  {
    fullname: 'Federico Conti',
    birthdate: '12/09/1984',
    age: 38,
    fiscalcode: 'CNTFDR84M12H501X',
    address: 'Via Torino, 567',
    placeOfBirth: 'Torino',
    nationality: 'Italiana',
    bio: "Federico Conti è un esperto di calligrafia, impegnato nel preservare e promuovere l'antica arte della scrittura manuale.",
    sex: 'M',
    eyeColor: 'Marroni',
    hairColor: 'Castani',
    height: 175,
    publishedArticles: 12,
    firstPublishDate: 2010,
    specialization: 'Calligrafia',
  },
  {
    fullname: 'Laura Rossi',
    birthdate: '18/06/1983',
    age: 39,
    fiscalcode: 'RSSLRA83M18H501U',
    address: 'Via Palermo, 789',
    placeOfBirth: 'Palermo',
    nationality: 'Italiana',
    bio: 'Laura Rossi è una biologa marina appassionata della diversità del regno animale. La sua ricerca si concentra sulla conservazione della vita marina.',
    sex: 'F',
    eyeColor: 'Azzurri',
    hairColor: 'Biondi',
    height: 170,
    publishedArticles: 25,
    firstPublishDate: 2003,
    specialization: 'Biologia Marina',
  },
  {
    fullname: 'Matteo Ferrari',
    birthdate: '25/01/1986',
    age: 36,
    fiscalcode: 'FRRMTT86M25H501T',
    address: 'Via Genova, 456',
    placeOfBirth: 'Genova',
    nationality: 'Italiana',
    bio: 'Matteo Ferrari è un musicista e compositore appassionato. Con il suo lavoro, cerca di trasmettere il potere universale della musica.',
    sex: 'M',
    eyeColor: 'Verdi',
    hairColor: 'Neri',
    height: 178,
    publishedArticles: 30,
    firstPublishDate: 2001,
    specialization: 'Musica',
  },
  {
    fullname: 'Chiara Romano',
    birthdate: '08/07/1988',
    age: 34,
    fiscalcode: 'RMNCHR88M08H501R',
    address: 'Via Bologna, 345',
    placeOfBirth: 'Bologna',
    nationality: 'Italiana',
    bio: 'Chiara Romano è una fotografa appassionata che cattura la bellezza della vita attraverso il suo obiettivo. Condivide storie visive uniche.',
    sex: 'F',
    eyeColor: 'Verdi',
    hairColor: 'Biondi',
    height: 165,
    publishedArticles: 15,
    firstPublishDate: 2012,
    specialization: 'Fotografia',
  },
  {
    fullname: 'Gabriele Martini',
    birthdate: '30/12/1981',
    age: 41,
    fiscalcode: 'MRTGRL81M30H501Q',
    address: 'Via Venezia, 678',
    placeOfBirth: 'Venezia',
    nationality: 'Italiana',
    bio: "Gabriele Martini è uno psicologo esperto nell'analisi dell'apprendimento umano. Il suo lavoro esplora le complessità della mente umana.",
    sex: 'M',
    eyeColor: 'Azzurri',
    hairColor: 'Castani',
    height: 180,
    publishedArticles: 25,
    firstPublishDate: 2005,
    specialization: 'Psicologia',
  },
  {
    fullname: 'Elena Bianchi',
    birthdate: '02/04/1989',
    age: 33,
    fiscalcode: 'BNCLEN89M02H501P',
    address: 'Via Padova, 123',
    placeOfBirth: 'Padova',
    nationality: 'Italiana',
    bio: "Elena Bianchi è un'appassionata studiosa di arte e architettura. Attraverso le sue opere, cerca di condividere la bellezza intrinseca di queste espressioni umane.",
    sex: 'F',
    eyeColor: 'Verdi',
    hairColor: 'Biondi',
    height: 170,
    publishedArticles: 18,
    firstPublishDate: 2007,
    specialization: 'Arte e Architettura',
  },
];
